### ISSUE TITLE
[BUG] Crashes when launched on ios 17.0

### ISSUE THREAD

**Issue by JTCGaming** [Torrekie/Battman#13]
**Describe the bug**
When opening the app, all that displays is a black screen. The app will sit like this on the screen until you close it out. It will not crash back to the home screen. I've tried the Trollstore install and tried to install through Sileo, but both produced the same result. I'll continue to use this app through Troll Store, and the logs provided will be from installing it over Troll Store.

**To Reproduce**
1. Install Battman 
2. Launch the app.

**Expected behavior**
I expected the app to launch like it had many many months ago when I first tried out the app. 

**Device info (please complete the following information):**
 - Device: [iPhone 13 base]
 - OS and OS Version: [iOS 17.0]
 - Battman version [v1.0]

**Additional context**
My iPhone has Trollstore installed and also has RootHide Bootstrap installed. I tried installing under both TS and Bootstrap, but had no success. It should be noted that I first tried under TS, then completely deleted the app. Then bootstrap and then completely deleted the app again. I then installed under TS once again. Further troubleshooting will be done through the Trollstore install unless otherwise stated. I will provide a launchd log that I pulled from my phone after trying to launch Battman under the TS installation. 

[01102025_193218_668_Iphone_13.log](https://github.com/user-attachments/files/22650905/01102025_193218_668_Iphone_13.log)

**Comment by Torrekie** [comment]
This is a known issue since roothide bootstrap seems also affecting TrollStore apps

**Comment by JTCGaming** [comment]
I’ve launched the app again and looked at the crash reporter. Unfortunately, nothing seems to make it to the crash reporter. My guess is because Battman doesn’t actually crash to the Home Screen but instead sits at a black screen for seemingly indefinitely. I even waited about 10 minutes and nothing came up in the crash reporter. I’ll send a screenshot of all the files in the crash reporter and also a screenshot of what the app does when launched. I launched the app at 10:30am local time. 

<img width="1170" height="2532" alt="Image" src="https://github.com/user-attachments/assets/c25934ff-3d2a-47a1-b0a2-55b3f710a1e9" />
![Image](https://github.com/user-attachments/assets/714a78f6-c9eb-4e27-a7fc-566a8cc5eb69)

**Comment by xiaoyong4ktv** [comment]
17.0 Trolls are also black screens

**Comment by LNSSPsd** [comment]
> I’ve removed the old version and installed the new version. Unfortunately I didn’t see any settings to prevent it from syncing with iCloud but this is likely expected, and the black screen issue still persists. However we do finally have a crash log because Battman did crash once. Every other time I tried launching after the crash, I’m met with the black screen. I’ll attach the crash log in hopes that it will help. I’ve changes it from .ips to .log because GitHub would not let me upload it as a .ips.
> 
> [Battman-2025-10-14-110902.log](https://github.com/user-attachments/files/22907992/Battman-2025-10-14-110902.log)

this specific issue is fixed on 46770d2f0232961a6fcccc54119a0460bb85bc6c, dk abt blackscreen though

**Comment by JTCGaming** [comment]
Just retried the latest version, and we are still getting a black screen when launching. Is there anything you may need to help you with fixing?

**Comment by JTCGaming** [comment]
I tried the commit [e87a9f9](https://github.com/Torrekie/Battman/commit/e87a9f9d88a77ccb58c66467b532dcb8c3e69475) with no luck. I could try the latest commit shortly, though.

**Comment by JTCGaming** [comment]
Dang. I won't try the latest then. If it helps, Batman did work for me once several months ago on a build that I grabbed from OneJailbreak on Twitter. Then the next build that was provided from the same source ended up being broken. If you want, I could try to find that build and send a link to it, or let you know the date it was confirmed to work?

**Comment by JTCGaming** [comment]
Sure thing! It will take me some time to dig up, and I am at work right now. When I get home, I will have a look for the exact post and let you know which one was working for me.

**Comment by LNSSPsd** [comment]
> I actually just decided to look now before I forget later. OneJailbreak posted a build to their website on April 25th, 2025. I can't download that build because they have since updated that page and made that build unavailable. If I had to guess, they posted the commit [83b0c5c](https://github.com/Torrekie/Battman/commit/83b0c5cdf8bb0270ca182134ddf1cc00a37b13f5). I can't download it from the actions tab, so I cannot confirm if it is working on 17.0. If there is a way to download, I'd be willing to go through and test which ones worked and which one broke it for 17.0. Anyway, OneJailbreak posted a new build on May 25th, 2025. Based on the time they posted the second build that broke 17.0 compatibility, I think it was the commit [892cfec](https://github.com/Torrekie/Battman/commit/892cfec87296f9ac4c97a5711e51c4ae02cd3735). Hopefully, that helps narrow down what broke the 17.0 compatibility. If there is a way I can download and test commits from that long ago, please let me know! I'd be willing to sit down and try.

commit 83b0c5cd

[battman_83b0c5c.zip](https://github.com/user-attachments/files/23894776/battman_83b0c5c.zip)

**Comment by JTCGaming** [comment]
Yup, that's the one! That one works on 17.0. The GUI shows up and everything.

**Comment by JTCGaming** [comment]
e7ad46b also works with 17.0. The GUI shows up, and everything works just like the last one from April. One thing to note is that when presented with the start up screen, where you can either accept or decline, there is no text except for accept and decline. Otherwise, it works perfectly! 

Opening up build 892cfec causes battman to crash back to the homescreen. No black screen or anything.
